# Generated by Django 3.1.2 on 2020-12-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_task',
            name='days',
            field=models.CharField(default='Deadline reached', max_length=100),
        ),
    ]
